services:
    - docker
before-install: 
    - docker build -t docker-react-img -f Dockerfile.dev .

script:
    - docker run docker-react-img npm run start -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-3-149383739282"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

      
